
DATABASE: "mydatabase.db"

REDIS:
  # Set this to an integer other than zero when using redis as db for queuing long callbacks. You need to run celery in order to process these tasks.
  # If this is set to false long_callbacks will use a cache inside the backend specified underneath
  URL: "redis://redis:6379/1"

backend:
  name: "filesystem_backend" # If REDIS URL is false this will use the Filesystem Backend named like the directory here
  threshold: 100


